version: '3'
services:
  alpine_container_1:
    image: alpine:latest
    command: ["tail", "-f", "/dev/null"]  # Keeps the container running
    networks:
      - my_network

  alpine_container_2:
    image: alpine:latest
    command: ["tail", "-f", "/dev/null"]  # Keeps the container running
    networks:
      - my_network

networks:
  my_network:
