project:
  type: website
  render:
    - "*.qmd"
    - "!scrapyard/"

website:
  title: "Jeffrey Fonseca"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects/index.qmd
      - blog/index.qmd
      - playground/index.qmd
      - guides/index.qmd
      #- about
    right:
      - icon: github
        href: https://github.com/moonpiedumplings
format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    anchor-sections: true



