project:
  type: website
  render:
    - "*.qmd"
    - "!scrapyard/"

website:
  title: "Jeffrey Fonseca"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - blog.qmd
      - playground.qmd
      - guides.qmd
      - about.qmd
    right:
      - icon: github
        href: https://github.com/moonpiedumplings
format:
  html:
    theme: darkly
    css: styles.css
    toc: true



