project:
  type: website
  render:
    - "*.*md"
    - "!scrapyard/"
    - "!not*"
    - "!norender*"

website:
  title: "Jeffrey Fonseca"
  site-url: https://moonpiedumplings.github.io
  navbar:
    left:
      - projects/index.qmd
      - blog/index.qmd
      - playground/index.qmd
      - guides/index.qmd
      - talks/index.qmd
      - writeups/index.qmd
      - text: Resume
        href: resume/index.qmd
      #- about
    right:
      - icon: rss
        href: https://moonpiedumplings.github.io/allposts.xml
      - icon: github
        href: https://github.com/moonpiedumplings
     
format:
  html:
    theme:
      light: 
        - light-styles.scss
        - flatly 
      dark: 
        - dark-styles.scss
        - darkly
    # css: styles.css
    toc: true
    anchor-sections: true



