project:
  type: website
  render:
    - "*.*md"
    - "!scrapyard/"

website:
  title: "Jeffrey Fonseca"
  site-url: https://moonpiedumplings.github.io
  navbar:
    left:
      - projects/index.qmd
      - blog/index.qmd
      - playground/index.qmd
      - guides/index.qmd
      - talks/index.qmd
      - writeups/index.qmd
      #- about
    right:
      - icon: github
        href: https://github.com/moonpiedumplings
format:
  html:
    theme:
      light: darkly
      dark: darkly
    css: styles.css
    toc: true
    anchor-sections: true



