---
title: "Hi, I'm Jeffrey Fonseca"
---

Over the summer before my freshman year of high school, I took a course at palomar college, CSNT 110, hardware and OS fundamentals. 

I first learned about the internals of computers during a summer course I took at Palomar college online before my freshman year of highschool — CSNT 110/ OS and Hardware Fundamentals. 

During my freshman year, when my laptop starting slowing down, I switched to a linux based operating system, in an attempt to make it faster, using knowledge I had obtained from that course. 

Since then, I have been tinkering, playing with software, and doing personal projects. However, when I was taking AP Computer Science Principles, during my senior year of high school, my teacher criticized me for being a maverick. I didn't bother with the group projects, working on my own projects, although I contributed back to the group often, but I didn't document what I do. 

As a response, I created this website. It isn't fancy, because frontend/website design isn't my preferred work. But for it does what I desire for it's purposes, and since then, I've been documenting my work, to create a portfolio for myself.

The [projects](projects/index.qmd) documents my progress in my personal projects. 

[Blog](blog/index.qmd) are my writings and ramblings.

[Playground](playground/index.qmd) is my shorter term experiments and testings.

[Guides](guides/index.qmd) are guides I've written to help other people. For example, I created the [duckdns guide](guides/duckdns/) because I was tired of helping people through that myself. 

[Talks](talks/index.qmd) are the presentations I do.
