---
title: "Linux and Programming Related Twitch Streamers"
description: ""
date: "2023-11-2"
execute:
  freeze: false
format:
  html:
    toc: false
    page-layout: article
---

I like to watch people program on twitch. Seeing people suffer with code reminds me that I am not alone.

I may be missing a few, so I will add them onto this list as I find them.

In addition to that, the notes on their content and OS are as of when I last watched them, so they may be inaccurate. If people stop being programmers, then I will take them offline.

In no particular order, here the ones I've seen around:

+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| Streamer                                                     | Content                                                                                                 | Linux User?                                                                                                        | Misc Notes                                                                         |
+==============================================================+=========================================================================================================+====================================================================================================================+====================================================================================+
| [het_tanis](https://www.twitch.tv/het_tanis)                 | Teaches linux, k8s devops, and ansible related things on stream.                                        | Windows as desktop, but uses xenserver (kinda unorthodox choice IMO) as a VM host for linux machines of every type | Killercoda courses can be found [here](https://killercoda.com/het-tanis)           |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| [cidermcdread](https://www.twitch.tv/cidermcdread)           | Just Chatting, Baldur's Gate, other various games.                                                      | Nixos                                                                                                              | Also discusses philosophical and political topics in a very engaging manner        |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| [chrissiecodes](https://www.twitch.tv/chrissiecodes)         | Python development, often for stream related features                                                   | Ubuntu in WSL                                                                                                      | Very active and knowledgable chat which is fun to be in.                           |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| [trshpuppy](https://www.twitch.tv/trshpuppy)                 | python, javascript, and CTF's/hacking                                                                   | Windows, but Kali in a VM                                                                                          |                                                                                    |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| [hedge_in](https://www.twitch.tv/hedge_in)                   | Low level operating system and machine learning                                                         | No                                                                                                                 | Often is studying these topics on stream for class                                 |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| [pwncollege](https://www.twitch.tv/pwncollege)               | Various college clacsses in the cybersecurity curriculum of Arizona State University                    | Various teachers some of whom probably use linux, but the format the classes are in does not let me see or ask     |                                                                                    |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| [cyberkaida](https://www.twitch.tv/cyberkaida)               | Low level operating programming, python. Reverse engineering                                            | Macos, but does work for linux like on the rasperry pi                                                             |                                                                                    |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| [lcolonq](https://www.twitch.tv/lcolonq)                     | Rust programming, or whatever language emacs uses.                                                      | Nixos                                                                                                              | Uses emacs window manager as his main wm.                                          |
|                                                              |                                                                                                         |                                                                                                                    |                                                                                    |
|                                                              |                                                                                                         |                                                                                                                    | Wrote his own vtuber rendering engine, which renders to ascii art in the terminal. |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| [badcop\_](https://www.twitch.tv/badcop_)                    | Gamejams, showing off content and programming for. Stream related features.                             | WSL                                                                                                                |                                                                                    |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| [theyagich](https://www.twitch.tv/theyagich)                 | Gamedev in Godot                                                                                        | Manjaro                                                                                                            |                                                                                    |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| [cybersteffie](https://www.twitch.tv/cybersteffie)           | Seems to be doing IRL more often recently, but has done programming work on stream                      | WSL                                                                                                                |                                                                                    |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| [piratesoftware](https://www.twitch.tv/piratesoftware/)      | Programming, and discussions of the software space                                                      | No                                                                                                                 |                                                                                    |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| [ambivalentbunnie](https://www.twitch.tv/ambivalentbunnie)   | Often studies for high level machine learning and data science classes on stream                        | No                                                                                                                 |                                                                                    |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| [ExpiredPopsicle](https://www.twitch.tv/expiredpopsicle)     | Gamdev/vtuber dev in godot. Also plays modded doom.                                                     | Debian Stable                                                                                                      |                                                                                    |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| [rw_grim](https://www.twitch.tv/rw_grim)                     | Work on open source source multi chat client [pidgin](https://pidgin.im/)                               | Debian Unstable, sometimes experimental                                                                            |                                                                                    |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| [hexadigital](https://www.twitch.tv/hexadigital)             | Various games                                                                                           | Manjaro on Desktop, Debian on server                                                                               | Does not talk, but does chat                                                       |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| [quantumapprentice](https://www.twitch.tv/quantumapprentice) | various programming projects                                                                            | Alternates between Linux Mint and Windows                                                                          |                                                                                    |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| [TheAltF4Stream](https://www.twitch.tv/thealtf4stream)       | Cloud, Devops, Kubernetes                                                                               | Mac on desktop                                                                                                     |                                                                                    |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| [Melkey](https://www.twitch.tv/melkey)                       | Web/Fullstack. ML/AI                                                                                    | Ubuntu I think, but I will have to confirm                                                                         |                                                                                    |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| [enlynn\_](https://www.twitch.tv/enlynn_)                    | Various programming                                                                                     | Endeavor OS                                                                                                        |                                                                                    |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| [purplelf](https://www.twitch.tv/purplelf)                   | Works at Gumroad, where she does Ruby and React, on stream                                              | Nobara                                                                                                             |                                                                                    |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| [anthonywritescode](https://www.twitch.tv/anthonywritescode) | Python developer                                                                                        | Current Ubuntu LTS in a virtual machine                                                                            |                                                                                    |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| [elvensourcerer](https://www.twitch.tv/elvensourcerer)       | Develops QT in python                                                                                   | Nixos                                                                                                              |                                                                                    |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| [lastmiles](https://www.twitch.tv/lastmiles)                 | Various things in Linux and FreeBSD. Setting up Cuda in a Bhyve VM running linux when I was last there. | FreeBSD 15 (as of 1/18/2024).                                                                                      |                                                                                    |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| [shrutivtuber](https://www.twitch.tv/shrutivtuber)           | Learning rust on stream                                                                                 | Arch Linux                                                                                                         |                                                                                    |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| [kodder](https://www.twitch.tv/kodder)                       | Various devops and system admin things                                                                  | Regolith on Pop_OS! on desktop, Proxmox on the one server I saw                                                    | Said he was gonna stream once a week on sunday                                     |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| [0xfaraday](https://www.twitch.tv/0xfaraday)                 | Go and python programming for cybersecurity related tools                                               | Kali Linux in a VM, I'm assuming windows on host                                                                   | Has participated as a blue teamer in [CCDC](https://www.nationalccdc.org/)         |
+--------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+