---
title: "Dreams of a Portable Future"
author: "Jeffrey Fonseca"
date: "2025-5-31"
categories: [playground]
format: 
  html:
    toc: true
    license: "CC BY-SA 4.0"
execute:
  freeze: false
draft: true
---


One of my dreams is to have portable equipment I can take with me when I go various places. It started with the first, a flyaway kit, but it has expanded.

# Flyaway Kit

I recently went to a conference where someone mentioned something called a "Fly away kit", which is essentially a server in a suitcase. "They may or may not be used for mobile threat hunting". 

Although I'm not really personally interested in an "[In Line Network Tap](https://solutions.nextcomputing.com/products/fly-away-kits/)", or "[meshed network nodes](meshed network nodes)", I do find the idea of a server in a suitcase to be very cool. It would be much easier to transfer around than a normal tower server form factor.

But, many of the "fly away kits" I've found have one thing in common: They won't tell you the price. And that indirectly tells me that I can't afford the price. 

Perhaps making my own would be cheaper? 

I don't plan to actually make one. But it's a fun thought experiment.

## The Case

The first step is the case. Recommened in a [relevant reddit post](https://www.reddit.com/r/homelab/comments/zog6n4/the_suitcase_server_project/
) were [Pelican Cases](https://business.pelican.com/discover/rack-mount-server-cases). Simply put, they could store a rack mount server, within a suit case, which is what I want to do.

Interestingly, [one fly away kit](https://www.forescout.com/products/flyaway-kit/) manufacturer seems to be doing exactly this, putting an Intel Xeon server in a Pelican Suitcase.

Another thing about pelican cases, is that it's possible to find [used cases on ebay](https://www.ebay.com/sch/i.html?_nkw=pelican+rack&_sacat=0&_from=R40&_trksid=m570.l1313), which is much cheaper than something completely new. 

## The Server

Pelican server rack cases have a certain set of dimensions, and are slightly smaller than what an average rack server will fit into.  I may require a [half rack](https://en.wikipedia.org/wiki/Rack_unit#Half-rack_configurations) server for this.



https://www.sealingtech.com/hardware/cyber-fly-away-kits/
https://solutions.nextcomputing.com/products/fly-away-kits/
https://www.ebay.com/
https://www.dell.com/support/manuals/en-us/poweredge-r630/r630_om_pub/dell-poweredge-r630-system-overview
https://duckduckgo.com/?t=ffab&q=site%3Areddit.com+half+length+servers&ia=web
https://www.reddit.com/r/HomeServer/comments/79n5t1/half_depth_rack_servers_anyone/
https://www.ebay.com/sch/i.html?_nkw=supermicro&_sacat=0&_from=R40&_trksid=p4432023.m570.l1313
https://www.ebay.com/itm/316544957957


In the far future, when I have more money, here are some vendors I might buy from:

* <https://www.raptorcs.com/>
* Ampere as a server

I also think GPU's are cool for machine learning, particularly chess.

## UPS

Power is also needed!

It's important to have some way to power the server for short or long periods it may be away from a plug while it is moved. 

Actually I don't think it's possible to power stuff remotely on the go. Oh well.

## Network

I think an ultra small router or a similar model is good.

One of the promising options is the [OpenWRT One](https://openwrt.org/toh/openwrt/one), it was used at the So Cal Linux Expo. 

The Wifi Router is for if I want to run CTF or share cool stuff in persons I can just have people join the wifi and do stuff. At the Linux User Group I am at right now, they used to do 


# Presentation Equipment

I would like equipment for impromptu presentations when I go to various events like my local Linux User Group. Recently, a member did a presentation, and he used a secondary monitor and spoke loudly, but we can do better than that. 


* [Portable Projector](https://www.amazon.com/TMY-Projector-Supported-Projection-Compatible/dp/B082F13J55) — Not exactly this, but something similar
  * wireless/bluetooth HDMI adapter, so that I can have my computer be away from the projecter when I present
* Directional Microphone: This allows me to record audio without it catching the audience members chattering or unecessary noises
* Camera: So I can record the presentation overall


# A Portable Workstation

I recently saw a [blogpost](https://holdtherobot.com/blog/2025/05/11/linux-on-android-with-ar-glasses/) ([archive](https://web.archive.org/web/20250526172436/https://holdtherobot.com/blog/2025/05/11/linux-on-android-with-ar-glasses/)), where they used an Android device, an external keyboard in mouse, in combination with XR glasses that replaced a monitor in order to get a portable working environment. 


- [] XR glasses. 
  - The glasses in the article don't support more than one monitor, but I think it would be really cool to work across like 3 or four at once. 
- [] Drawing Tablet: I already have a Wacom Intuos Bluetooth
- [] Input Devices (keyboard + mouse)
  - Do I need a keyboard, or can I just use my laptop keyboard.  
- [] Rooted Android Device/Tiny computer

# A Portable Gaming Setup

Right now I have a Gamesir X2 controller. It's a fine controller, but it was overpriced for what it offers, and it requires a proprietary app that Google Play keeps reporting as malware to do the configurations. 

I want more than just a phone that is also a switch though. I also want may want an entire home console setup, via the flyaway kit and the projector, which may entail a controller. I would like a nice portable controller. 

I think the smallest full joystick controller that people still find comfortable are the 8bitdo Lite 1/2 and the 8bitdo SN30. 

Another thing I have been keeping my idea on is the [mcon](https://www.kickstarter.com/projects/ohsnapofficial/mcon-the-switchblade-of-mobile-controllers-by-ohsnap) a pull out controller for phones. However, it's not out yet.

