---
title: "First job, an internship at cirrascale"
description: ""
date: "2023-7-10"
categories: [linux]
execute:
  freeze: false
---


Cirrascale is a San Diego company that offers managed cloud computing, targeted at AI. Before my vacation, I took a tour of their hosting center. It honestly had me awestruck, seeing rack upon rack of water cooled servers.

2023-7-10

First day. It was pretty nice. My skills with managing linux, containers, and virtual machines came in handy. I took initiative and stepped up when a task was offered, which was tough because I was so new. My heart was literally racing and I felt so nervous, but I didn't take on more than I could handle and I made good progress on it in that same day. In addition to that, I collaborated with the other interns on things. Overall, it was a lot of fun, and the people were very friendly. 

2023-7-12

In the last two days I feel like I have done a lot, despite being so new.  I helped another intern install Ubuntu linux, and I am now working on another project, creating a proxmox image with packer to deploy using maas.

2023-8-1

Since then, I have completed created an image, although I haven't tested yet. In addition to that, I got to post all my code on github: 

<https://github.com/moonpiedumplings/proxmox-maas>

2023-8-26

Alright, my original intention was for this to be a regular or semi regular type blog thing, but that was very boring, as most days were simply spent grinding away at whatever problems I was working on. 

So I'm just going to put an overview and reflection here, after I have done the internship. 


I worked on two major projects, which ate up the majority of my time. 

The first was [proxmox-maas](https://github.com/moonpiedumplings/proxmox-maas). Maas is an automated deployment method created by canonical, and it allows you to deploy configured ubuntu servers to virtual machines, or usually more valuably, bare metal machines. In Cirrascale, they were using Maas to deploy Ubuntu, and using MAAS to configure things like networking on these machines. MAAS can deploy other operating systems, but you have to create an image which it can deploy. I created a proxmox image, so that they could deploy it to bare metal machines rapidly.

The other project I created was assisting in planning a setup where they use rancher to deploy kubernetes. I started out with my notes on onedrive, but eventually I got annoyed and put them on [github sites](https://moonpiedumplings.github.io/rancher-ops/). I created a simple docker-compose file to allow people to quickly up rancher for testing purposes, and I noted it on that page. In addition to that, I also documented installing k3s clusters with calico rather than rancher, installing vcluster, installing kata-containers, and other kubernetes management operations. 


Overall, it was a great learning experience. I had an abstract understanding of what production environments required, but it was cool to work with those in production environments.


