---
title: "Being an internet helper"
date: "2023-10-23"
categories: [linux, _blog]
format:
  html:
    code-fold: true
    code-summary: "Show the code"
    code-block-background: true
execute:
  freeze: true
---

*The below is my "literacy narrative essay", for an english class*

I was so close to hacking this system. Using a USB thumb drive as a boot device, I booted a different operating system on the computer, which originally ran windows. I then used some digital tools to enable the local administrator account, in a passwordless mode. When I removed the USB thumb drive, and restarted the machine, it returned to the innocuous login prompt, asking me to sign in with my school credentials. I ignored that, and signed into the admin account instead. I’m in.

It was a different kind of puzzle. But just like any other puzzle, I solved it for the gratification, rather than there being some end goal. Eventually, the computer’s were reset, and all my hard work was lost.

Later, when my computer was becoming too slow, I felt an itch in the back of my mind again. A new puzzle.

How do I make my computer faster?

I was tinkering already, and I had some ideas of how to make it faster, but I needed reassurance. Unfortunately, not all puzzles can be solved alone. I ended up asking for help on the internet.

Although 4 years ago, and the post has since been deleted, although not by me, I still remember what I asked for. I wanted to know how to replace the lowest level of software on my computer, the operating system, going from the slower Windows that is available on most devices by default, to the more difficult to use, but faster, Linux. However, I did not want to break the existing Windows install, and I also wanted to have “save points” of my linux installation, so that I could tinker and then restore my system to a previous state, giving my system some resilience.

The users were patient, and kind, and although they didn’t hold my hand for the entire process, they pointed me in the right directions, teaching me terminology and pointing me to resources that I could use to help myself. Eventually, I managed to solve that puzzle, and some variations of the changes I made, I do on all computers I own today.

After I ran out of puzzles to solve, I began solving other people’s puzzles. I would watch the forums religiously, viewing the newest posts first, so I could contribute before someone else. Sometimes, things were easy, and it was simply a case of a newer user not knowing what to search for, and I could point them in the right direction. For example, people would often ask if their hardware is compatible with Linux, so I would point them to a site that extensively documents hardware compatibility. With every reply thanking me, I felt immense gratification.

Of course, things wouldn’t always be as simple as that. Often, users weren’t simply seeking to do something, but to understand something as well. In this case where existing resources weren’t enough, I had to explain step by step.

One user was curious about how Linux software distribution works. What makes it different from Windows, or Mac, they asked? As painful as it was to type from my phone, I presented the unbiased reality of how Linux software management is objectively superior. Because some things, you have to explain personally, and you can’t point people to external resources.

Very often, new users don’t know how to ask for help, and you have to request for more information from them. For some reason, people often have trouble running games on Linux, but they won’t mention what game they are trying to play? I don’t understand how people understand how to get help if they don’t give enough information, but asking for help isn’t really something that comes intuitively to people.

Of course, once I know what game they play, I can give more detailed help. One time, there was a user who had nothing but a chromebook, but desired to get more performance out of it so that they could play one of my favorite games. Over the course of several days via purely discord text chats, I helped this person with installing Linux and installing the game on an unsupported device and operating system. But despite all that, their efforts didn’t bear much fruit, and they ended up giving up.

Although frustrating to see someone give up, it happens sometimes. On the other end, I’ve had to give up on cases as well. In one online community I followed, there was a constant influx of users asking similar or even the same questions. Although many people, including me, first started out by answering them, eventually the community got tired and sometimes even hostile to such users.

On the internet, “Help Vampires” are one type of person that appears in forums. This term refers to people who are unwilling to do the bare minimum of research, or put any effort into any problem. An infrequent occurrence on the internet, It’s difficult to help someone if they don’t help themselves. In many cases, it’s impossible.

A similar thing happened when a user was attempting to play a video game on Linux, and got an error about the kernel (the lowest lowest level of software, part of, but also under the operating system) not supporting a feature. Because of this, they were attempting to install a new kernel. However, what I found strange was the error message was requesting a feature that normally is not needed. The actual issue this user was encountering was that they enabled a non-necessary feature in their game launcher.

This is a common occurrence, common enough that there is actually a term for it: the XY problem where a user attempts to get help with their attempted solution, rather than their actual problem. Rather than explaining the whole XY problem, I would usually refer people to this website: https://xyproblem.info/.

In another post, a user asked if anyone has experience with the integration of two pieces of technology, one being a VPN, and the other being a management platform. They gave no other information. What this user was actually asking was: “Is there anybody around with experience with these techs that is willing to look into my problem, including extracting what my actual problem is me because I can’t be bothered to explain it?”

This is another occurrence on the internet that happens frequently enough that there is a term to refer to it, and a website which I refer people to: https://dontasktoask.com. Don't ask your question, simply ask it to save everybody’s time.

As long as you have technical literacy, giving help to people troubleshooting on the internet is easy. Doing it nearly daily, for 4 years, without being burned out, is not. Many user’s helped out for a short period of time, to give back to the community, before becoming burned out and stopping. There were very few constants, people you could recognize just by their username, because they were that consistent.

I was one of them. Linux gave me a lot. Rather than gaming, I was tinkering. Working with Linux is likely what my job will be. But I didn’t, and still don’t, have the particular skill set to contribute to the Linux community through programming. I do intend to learn, but at the same time, I’ve come to love being a “helper” on the internet. The pleasure I get is threefold, one part for solving a problem, another for helping a stranger, and yet another for giving to this community that was willing to invest in me, back when I was barely a teen and didn’t know much. 

