---
title: "Jeffrey Fonseca — Resume"
execute:
  freeze: false
format: 
  html:
    toc: false
    page-layout: full
    anchor-sections: true
    #grid:
    #  margin-width: 450px
    # body-width: 600px
#classoption:
#  - twocolumn
  # the github CI/CD environment might not have latex packages, which are needed for rendering pdf. Keeping this commented to avoid problems. 
  pdf:
   output-file: Fonseca_Jeffrey_Resume
   output-ext: pdf
   papersize: letter
   documentclass: article
   # documentclass: [headsep=0]{scrartcl}
   title: "Jeffrey Fonseca — Resume \\vspace{-1cm}"
   # subtitle: "Test title"
   # abstract: "Test Abstract"
   fontsize: 10pt
   linestretch: 0.75
   geometry:
     - top=-10mm
     # - top=0.5in
     - bottom=0.5in
     - right=0.5in
     - left=0.5in
     - heightrounded
     - headheight=0pt
     - headsep=0pt
     # - showframe
   # mainfont: "Font Awesome 6 Free"
   include-in-header:
     - text: |
        \setlength{\headsep}{0pt}
        \usepackage{fontspec}
        \newfontfamily{\fabrands}{Font Awesome 6 Brands}
        \newcommand{\faicon}[1]{{\fabrands #1}}
        \newcommand{\cf}[2][12]{\fontspec{Font Awesome }\fontsize{#1}{#1}\selectfont #2}
        \newcommand{\fatext}[1]{{\fontspec{Font Awesome 6 Free}#1}}
  #  include-before-body: | 
  #     "\setlength{\headsep}{0pt}"
  #  - file: preamble.tex
---
\vspace{-0.4cm}
::: {.content-visible when-format="html"}

Resume QR Code

<details><summary>Show QR Code</summary>

{{< qrcode https://moonpiedumplings.github.io/resume/ >}}

</details>

:::


| |
|:------:|
| {{< fa envelope >}} `jeff.fonseca777 [at] gmail.com` • {{< fa phone >}} +1-573-\*\*\*-\*\*\*\* |
| [Github {{<fa brands github >}} : `moonpiedumplings`](https://github.com/moonpiedumplings) • [Website/{{< fa blog >}}: moonpiedumplings.github.io ](https://moonpiedumplings.github.io/) |

# Summary
Avid user of Linux {{<fa brands linux >}} and related technologies for 5 years, intimately familiar with them through personal projects, daily usage, and teaching others. Proficient in both operations, and technical writing/documentation.

I have a site where I document all my work, write about tech, and post guides for other to use: [moonpiedumplings.github.io](https://moonpiedumplings.github.io/)
\vspace{-0.2cm}

# Professional Experience
\vspace{-0.2cm}

<hr>[$\hrulefill$]{.content-visible when-format="pdf"}

**Internship at Cirrascale Cloud** \hfill Date: 7/10/2023 - 8/26/2023

* Installed PFSense {{< fa shield-alt >}} on Proxmox
* [Used packer to automate creation of a MAAS image that deploys Proxmox](https://github.com/moonpiedumplings/proxmox-maas/)
* [Documented K3's kubernetes, vcluster, and Kata-containers on Nvidia GPU's for machine learning operations](https://moonpiedumplings.github.io/rancher-ops/)
* Assisted in building physical servers {{< fa server >}}, including doing tasks like installing storage {{< fa hdd >}}, memory {{< fa memory >}}, or Nvidia GPU's
<hr>[$\hrulefill$]{.content-visible when-format="pdf"}

**WUOTT — Behevioral Health Clinic** \hfill Date: 2016 - Still ongoing. 

It's my mother's business, so I help out a little bit when needed

* General helpdesk and tech support
* Deployed Meshcentral on an Ubuntu {{< fa brands ubuntu >}} VPS using Docker Compose {{< fa brands docker >}} so I could access, manage, and troubleshoot <!--7--> Windows {{< fa brands windows >}} devices remotely

\vspace{-0.3cm}
# Independent Organizations
\vspace{-0.4cm}
<hr>[$\hrulefill$]{.content-visible when-format="pdf"}

**Layer 8 Club at Cal State Northridge** \hfill Date: Fall 2023 to Ongoing

CSUN competes in a cybersecurity competition, [CCDC](https://www.nationalccdc.org). Much of the work here is for that.  

* [Automated firewalls, backups, password shuffling and container management via Ansible on Linux](https://github.com/CSUN-CCDC/CCDC-2023/tree/main/linux/ansible/roles)
* [Designed a reproducible development environment for Linux {{< fa brands linux >}}, Windows {{< fa brands windows >}}, and Mac {{< fa brands apple >}} using Nix {{< fa snowflake >}}](https://moonpiedumplings.github.io/guides/ccdc-env)
* Introduced and taught people Linux {{< fa brands linux >}}, concepts, and related software {{< fa brands docker >}}, {{< fa terminal >}}, {{< fa brands wordpress >}}, {{< fa database >}}, {{< fa shield-alt >}}, {{< fa network-wired >}}
* [Did a presentation on containers {{< fa brands docker >}} that run on Linux {{< fa brands linux >}} (with recording)](https://moonpiedumplings.github.io/talks/containers)
* [Did other presentations on Ansible and Quarto/Github Pages](https://moonpiedumplings.github.io/talks/)
* Completed multiple [NICE challenges](https://nice-challenge.com/), involving Linux {{< fa brands linux >}}, terminal {{< fa terminal >}}, and simple database {{< fa database >}} management. Wrote [5 Writeups](https://moonpiedumplings.github.io/writeups/) to assist my teammates.
<hr>[$\hrulefill$]{.content-visible when-format="pdf"}
\vspace{-0.4cm}

# Personal/Educational Projects
\vspace{-0.4cm}
* Deployed a Minecraft {{< fa cubes >}} server using Podman to an Oracle Cloud VPS
* Built CI/CD Pipelines using GitHub {{< fa brands github-square >}} actions and Docker {{< fa brands docker >}}, to deploy to an AWS {{< fa brands aws >}} EC2 VPS, for a class project for AP CSP
* Dockerized Node.js {{< fa brands node >}}{{< fa brands js >}}, Python {{< fa brands python >}}, and Java {{< fa brands java >}} applications
* Wrote technical documentation to assist students and teachers in AP CSP (E.g: [duckdns](https://moonpiedumplings.github.io/guides/duckdns/))
* [Deployed Kasmweb on a highly performance optimized Ubuntu {{< fa brands ubuntu >}} VPS](https://moonpiedumplings.github.io/projects/setting-up-kasm/)
* Worked towards [packaging Kasmvnc](https://moonpiedumplings.github.io/projects/setting-up-kasm/) and [OpenStack](https://moonpiedumplings.github.io/projects/openstack-on-nixos/) {{< fa cloud >}} via Nix
* [Deployed a point to site Wireguard VPN connection between my router and a VPS](https://moonpiedumplings.github.io/projects/build-server-2/#router-networking)
* [Installed OpenStack on Rocky {{< fa brands redhat >}} Linux {{< fa brands linux >}} using Kolla-Ansible](https://moonpiedumplings.github.io/projects/build-server-2/)

Current personal projects can be found on [my website](https://moonpiedumplings.github.io/), where I document my work as go. I make it a point to pick challenges beyond my current ability. I don't always succeed, but I always grow in the process.

\vspace{-0.4cm}
# Education
\vspace{-0.3cm}
The items in this section are in chronological order, from things I did first to things I did most recently.

* Palomar Community College
    + Intro to OS/Hardware Fundamentals (CSNT 110)
* Graduated from Del Norte High School
    + AP Calculus AB
    + AP Computer Science Principles (AP CSP) {{< fa brands python >}}
* Cal State Northridge Computer Science BS — expected graduation 05/27
  - [X] Introduction to Algorithms and Programming (COMP 110/L) {{< fa brands java >}}
  - [X] Data Structures in Java (COMP 182/L) {{< fa brands java >}}
  - [ ] Calculus 2 (CALC150B)