---
title: "Jeffrey Fonseca — Resume"
execute:
  freeze: false
format: 
  pdf:
   output-file: Fonseca_Jeffrey_Resume
   output-ext: pdf
   papersize: letter
   documentclass: article
   title: "Jeffrey Fonseca — Resume \\vspace{-1cm}"
   fontsize: 10pt
   linestretch: 0.75
   geometry:
     - top=-10mm
     - bottom=-10mm
     - right=0.5in
     - left=0.5in
     - heightrounded
     - headheight=0pt
     - headsep=0pt
   include-in-header:
     - text: |
        \setlength{\headsep}{0pt}
      #\usepackage{fontspec}
      #\usepackage{xcolor}
      #\usepackage[hidelinks]{hyperref}
# Prevent links from being colored
colorlinks: false
---
\vspace{-0.4cm}

\vspace{-0.6cm}

| |
|:------:|
|  `jeff.fonseca777 [at] gmail.com` |
| [GitHub  : `moonpiedumplings`](https://github.com/moonpiedumplings) • [Website: moonpiedumplings.github.io](https://moonpiedumplings.gitHub.io/) • [LinkedIn: Jeffrey Fonseca](https://www.linkedin.com/in/jeffrey-fonseca-4242521a4/) |

\vspace{-0.8cm}



# Summary

\vspace{-0.4cm}

$\hrulefill$
\vspace{-0.2cm}

Avid user of Linux, Kubernetes, and other cloud native technologies, intimately familiar with them through work experience, personal projects, daily usage, and teaching others. Proficient in operations and technical documentation of cloud native systems.

\vspace{-0.4cm}


# Education
\vspace{-0.5cm}

$\hrulefill$
\vspace{-0.2cm}

Cal State Northridge Bachelors in Computer Science — expected graduation 05/27

\vspace{-0.2cm}

$\hrulefill$
\vspace{-0.4cm}

# Work Experience
\vspace{-0.4cm}
<br>$\hrulefill$

\vspace{-0.2cm}

**Cirrascale Cloud** \hfill Date: 7/10/2023 - 8/26/2023

\vspace{-0.2cm}

MLOps Intern   \hfill San Diego, California

\vspace{-0.2cm}

* Deployed a virtualized firewall, controlling traffic flow between networks
* [Enabled remote, one click automated installs of Proxmox using MAAS at no cost](https://github.com/moonpiedumplings/proxmox-maas/)
* [Deployed Rancher for RBAC and GUI operations of Kubernetes clusters](https://moonpiedumplings.github.io/rancher-ops/)
* [Installed virtualized Kubernetes clusters to allow for customers to share GPU's on physical hosts securely, enabling more than a single tenant per cluster at no cost](https://moonpiedumplings.github.io/rancher-ops/)
* Built physical servers, installed storage, memory, and Nvidia GPU's

\vspace{-0.2cm}

$\hrulefill$

\vspace{-0.2cm}

**Healing Wells — Behevioral Health Clinic** \hfill Date: 2016 - 2022

\vspace{-0.2cm}

Helpdesk Support Technician \hfill San Diego, California

\vspace{-0.2cm}

* Troubleshooted Windows technical issues, offering on call technical support
* Deployed an open source MDM at zero cost on previously unmanaged devices, enabling remote support for employees
* Added contact forms and scheduling features to the WordPress site

\vspace{-0.2cm}

$\hrulefill$

\vspace{-0.1cm}

**Layer 8 Cybersecurity Club** \hfill Date: Fall 2023 to Present

\vspace{-0.1cm}

President

\vspace{-0.2cm}

* 26+ users taking advantage of services deployed and maintained using Kubernetes and GitOps.
* Deployed IAM for invites, easy onboarding, and RBAC of new users (Authentik)
* [Offering educational virtual machines and networks for students via Incus, a self hosted cloud](https://moonpiedumplings.GitHub.io/projects/build-server-6/#incus-configuration)
* Serving cloud based instant access Kali Linux Desktops via Coder
* Running twice weekly meetings, workshops, and lectures for members

\vspace{-0.2cm}

Collegiate Cyber Defense Competition Team Captain

\vspace{-0.2cm}

* Actively defended 30 machines, in order to keep an an environment online against professional red teamers
* [Scripted incident response and security tasks on Windows and Linux using Ansible](https://github.com/csunlayer8/ccdc)
* [Led our team to regionals twice, taking 7th among 24+ other collegiate teams](https://bsky.app/profile/wrccdc.org)
* [Automated onboarding of users via Nix](https://moonpiedumplings.github.io/guides/ccdc-env/)


$\hrulefill$
\vspace{-0.6cm}

# Projects

\vspace{-0.5cm}

$\hrulefill$

\vspace{-0.2cm}

**[Flask Stocks App](https://github.com/Ryanrob327/P3T3_stocks)**

\vspace{-0.2cm}

* Dockerized Node.js and Python web servers
* Automatically built and deployed to Amazon EC2 using Github Actions CI/CD

\vspace{-0.2cm}

**[Virtual Desktop Infrastructure Service For Students](https://moonpiedumplings.GitHub.io/projects/setting-up-kasm/)**

\vspace{-0.2cm}

* Deployed a browser based virtual desktop infrastructure to enable students limited to chromebooks to operate with a full software development environment
* Applied optimizations, including memory compression and deduplication to allow for 2 additional desktop sessions on a 4 GB of ram AWS EC2 instance

\vspace{-0.2cm}

**The DormLab**

\vspace{-0.2cm}

* Kubernetes based self hosted cloud, with services like: Incus, Coder, Openfga, Authentik, Forgejo, and OpenWebUI
* [Deployed Openstack Cloud using Kolla-Ansible](https://moonpiedumplings.github.io/projects/build-server-2/#installing-openstack), then [again using Openstack-Helm on Kubernetes using Ceph](https://moonpiedumplings.github.io/projects/build-server-6/#openstack)
  * Floating IP addresses: Virtual Machines could be assigned a public IP address from a /24 subnet, enabling users to expose their services to the internet
* Hosting OpenWebUI and Ollama for self hosted, data sovereign generative AI operations

<!--
* Deployed a Minecraft server using Podman to an Oracle Cloud VPS
* Built CI/CD Pipelines using GitHub  Actions and Docker, to deploy to an AWS  EC2 VPS, for a class project for AP CSP. Over 40 students utilized my pipelines for auto deployment
* Dockerized Node.js, Python, and Java  applications
* Wrote technical documentation to assist students and teachers in AP CSP (E.g: [duckdns](https://moonpiedumplings.GitHub.io/guides/duckdns/))
* [Deployed Virtual Desktop Infrastucture for students limited to chromebooks](https://moonpiedumplings.GitHub.io/projects/setting-up-kasm/)
* [Deployed a point to site Wireguard VPN connection between my router and a VPS](https://moonpiedumplings.GitHub.io/projects/build-server-2/#router-networking)
* [Installed OpenStack on Rocky  Linux  using Kolla-Ansible](https://moonpiedumplings.GitHub.io/projects/build-server-2/)
* [Installed Openstack using Openstack-Helm on Kubernetes](https://moonpiedumplings.github.io/projects/build-server-6/#openstack-install-cont)
* [Deployed a Kubernetes cluster using FLuxCD (GitOps)](https://moonpiedumplings.GitHub.io/projects/build-server-5/)
-->
\vspace{-0.4cm}

$\hrulefill$
\vspace{-0.5cm}

# Skills
\vspace{-0.5cm}
$\hrulefill$


**Cloud**: Kubernetes, Terraform, Docker/Podman, AWS, Incus/LXD, Proxmox, Openstack

**CI/CD**: GitHub Actions, Forgejo, Helm, FluxCD, ArgoCD

**Languages**: Python, Ansible, C#, Go, Java, Bash

**Linux**: Red Hat (Rocky, Alma, etc), Debian, Ubuntu, Arch, NixOS, Alpine

**Security**: Secret Management (Sops), IAM (Authentik), RBAC, ReBAC (OpenFGA), Active Directory

**Databases**: Postgres, MySQL/Mariadb, Redis/Valkey