---
title: "CCDC Learning Resources"
date: "2023-10-28"
categories: [guides]
format:
  html:
    code-fold: true
    code-summary: "Show the code"
    code-block-background: true
execute:
  freeze: false
---

This document was designed for our CSUN CCDC team, but since it's useful, I am putting it on my personal blog as well. 

Prerequisites:

* Creating a [virtual machine](https://en.wikipedia.org/wiki/Virtual_machine). Install the [virtualbox](https://www.virtualbox.org/) software, and download the [linux mint image from osboxes.org](https://www.osboxes.org/linux-mint/). With this, the activities in the below resources will be a lot more interactive. 
* Github account. Join our CSUN-CCDC organization

# Linux

## Guided

Some resources to get started on your linux journey. 

<https://linuxjourney.com/> 

Linuxjourney is a very good guide, but it has some stuff not relevant to what we are doing. 

You don't need to networking nomad, but you do need to do grasshopper and journeyman. 

Out of the stuff on those two programs, skip:

* Text-fu
* Text-fu advanced

We will probably either be using nano or automation/scripting to edit files.

* Boot processes

* From init, skip anything not relevant to systemd. No one uses upstart or systemv anymore.

# Ansible:

[this video series](https://www.youtube.com/playlist?list=PLT98CRl2KxKEUHie1m24-wkyHpEsa4Y70) by learnlinuxtv. 

Follow along using your virtual machine. You can setup ssh, or you can have an inventory of `localhost` to run playbooks on the same machine as you are currently on. 

Once you have experimented with ansible enough, you can also experiment with running our ansible playbooks.


# Windows

## Active Directory

[A cat explains active directory](https://www.youtube.com/watch?v=zyud11pz40s)

High level overview, covering some of the history and many of the concepts behind active directory. 

[A cat explains kerberos](https://www.youtube.com/watch?v=7kWdCzswPIc)

I have not watched yet, but based on the above video, which mentions how active directory includes kerberos, it is probably relevant. 


[Microsoft's Intro to AD](https://learn.microsoft.com/en-us/training/modules/introduction-to-ad-ds/)

[GOAD - Game of Active Direcotyr](https://github.com/Orange-Cyberdefense/GOAD)

This is a highly insecure active directory which can be auto deployed to hyperv, proxmox, virtualbox, or azure. It uses a mix of ansible, terraform, and packer to provision and deploy.









