---
- name: Provision lxd on a debian vm
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Ensure /etc/apt/keyrings/ exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: Download file
      ansible.builtin.get_url:
        url: https://pkgs.zabbly.com/key.asc
        dest: /etc/apt/keyrings/zabbly.asc
        mode: '0644'
    - name: Create repo file
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/zabbly-incus-stable.sources
        content: |
          Enabled: yes
          Types: deb
          URIs: https://pkgs.zabbly.com/incus/stable
          Suites: bookworm
          Components: main
          Architectures: amd64
          Signed-By: /etc/apt/keyrings/zabbly.asc
    - name: Install relevant packages
      ansible.builtin.apt:
        update_cache: true
        name:
          - incus
          - incus-ui-canonical
          - incus-client
          # - lxd-agent
          - dnsmasq-base
          - qemu-system-x86
          - btrfs-progs
          - podman
        install_recommends: true
        state: present
    - name: add vagrant user to lxd group
      ansible.builtin.user:
        name: vagrant
        groups: ['incus']
        append: true
    - name: Edit incus configs, to enable the https address
      ansible.builtin.shell: |
        incus config set core.https_address :8443
    - name: restart incus
      ansible.builtin.service:
        name: incus
        state: restarted
    - name: Create persistent lxdware data
      ansible.builtin.file:
        path: "/root/lxdware"
        state: directory
        mode: '0755'
    - name: Run podman container
      containers.podman.podman_container:
        name: lxd-dashboard
        image: docker.io/lxdware/dashboard:latest
        network: host
        # ports:
        #   - 80:80
        volumes:
          - /root/lxdware:/var/lxdware
        # env:
        #   ADMIN_PASS: lxdware
    # - name: Print vm ip address
    #   ansible.builtin.debug:
    #     msg: "ip is {{ ansible_default_ipv4[eth0] }}"
